name = "prim-parser"
version = "0.1.0"
defaultTargets = ["PrimParser"]

[leanOptions]
pp.unicode.fun = true
pp.fieldNotation = false
autoImplicit = false

[[lean_lib]]
name = "PrimParser"

[[lean_lib]]
name = "Examples"

[[lean_lib]]
name = "Tests"

[[lean_lib]]
name = "BenchGen"

[[lean_exe]]
name = "bench"
root = "Bench"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"
